# Generated by Django 4.2 on 2024-06-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='books',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customers',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sale_price',
        ),
    ]
